'use client';
import { useState, useTransition } from 'react';
import { confirmImport, remapImport, validateImport } from '@/app/(admin)/admin/data-management/actions';
import { IMPORT_TYPES } from '@/lib/import/types';

export default function DataManagementForm() {
  const [result, setResult] = useState<{ batchId: string; totalRows: number; columns?: string[]; mapping?: Record<string, string>; issues: { rowNumber: number; errorCode: string; errorMessage: string; severity: string }[] } | null>(null);
  const [pending, startTransition] = useTransition();
  return <section className="panel"><h2>File Upload</h2><form action={(formData) => startTransition(async () => { try { setResult(await validateImport(formData)); } catch (error) { setResult({ batchId: '', totalRows: 0, issues: [{ rowNumber: 0, errorCode: 'IMPORT_ERROR', errorMessage: error instanceof Error ? error.message : '업로드에 실패했습니다.', severity: 'ERROR' }] }); } })}><input accept=".csv,.xlsx" name="file" required type="file" /><select defaultValue="usage_history" name="importType">{IMPORT_TYPES.map((type) => <option key={type} value={type}>{type}</option>)}</select><select defaultValue="append" name="importMode"><option value="append">append</option><option value="upsert">upsert</option><option value="replace">replace</option></select><button className="button button-primary" disabled={pending} type="submit">{pending ? '검증 중...' : 'Parse · Preview · Validation'}</button></form>{result ? <div className="import-result"><p>Preview 행 수: {result.totalRows}</p>{result.mapping ? <form action={(formData) => startTransition(async () => { const mapping = Object.fromEntries(Object.keys(result.mapping ?? {}).map((target) => [target, String(formData.get(`map_${target}`) ?? '')])); const remapData = new FormData(); remapData.append('batchId', result.batchId); remapData.append('mapping', JSON.stringify(mapping)); setResult(await remapImport(remapData)); })}><p>컬럼 매핑 확인/수정</p>{Object.entries(result.mapping).map(([target, source]) => <label key={target}>{target}<input defaultValue={source} name={`map_${target}`} /></label>)}<button className="button" disabled={pending} type="submit">매핑 적용 후 재검증</button></form> : null}<p>검증 결과: {result.issues.length ? `${result.issues.length}건의 오류/경고` : 'SUCCESS'}</p>{result.issues.slice(0, 10).map((issue, index) => <p key={`${issue.rowNumber}-${index}`} className={issue.severity === 'ERROR' ? 'text-critical' : 'text-warning'}>{issue.rowNumber}행 {issue.errorCode}: {issue.errorMessage}</p>)}{result.batchId && !result.issues.some((issue) => issue.severity === 'ERROR') ? <form action={(formData) => startTransition(async () => { await confirmImport(formData); setResult(null); window.location.reload(); })}><input name="batchId" type="hidden" value={result.batchId} /><button className="button" disabled={pending} type="submit">사용자 확인 후 Import 실행</button></form> : null}</div> : null}</section>;
}
