-- STEP 4: 파일 적재 파이프라인의 staging, 검증, 이력, rollback 구조

create table if not exists core.upload_batch (
  batch_id uuid primary key default gen_random_uuid(),
  file_name text not null,
  import_type text not null,
  import_mode text not null check (import_mode in ('append', 'upsert', 'replace')),
  total_rows integer not null default 0,
  success_rows integer not null default 0,
  warning_rows integer not null default 0,
  error_rows integer not null default 0,
  status text not null default 'UPLOADED' check (status in ('UPLOADED', 'VALIDATED', 'IMPORTED', 'ROLLED_BACK', 'FAILED')),
  uploaded_by uuid not null references auth.users(id),
  uploaded_at timestamptz not null default now(),
  imported_at timestamptz
);

create table if not exists core.import_staging (
  staging_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null,
  original_data jsonb not null,
  mapped_data jsonb not null default '{}'::jsonb,
  validation_status text not null default 'PENDING' check (validation_status in ('PENDING', 'SUCCESS', 'WARNING', 'ERROR')),
  unique (batch_id, row_number)
);

create table if not exists core.column_mapping (
  mapping_id bigint generated by default as identity primary key,
  import_type text not null,
  source_column text not null,
  target_column text not null,
  confirmed_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  unique (import_type, source_column)
);

create table if not exists core.validation_error (
  validation_error_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null,
  field_name text,
  error_code text not null,
  error_message text not null,
  severity text not null check (severity in ('WARNING', 'ERROR')),
  original_value text,
  created_at timestamptz not null default now()
);

create index if not exists import_staging_batch_idx on core.import_staging(batch_id, row_number);
create index if not exists validation_error_batch_idx on core.validation_error(batch_id, row_number);

alter table core.upload_batch enable row level security;
alter table core.import_staging enable row level security;
alter table core.column_mapping enable row level security;
alter table core.validation_error enable row level security;

grant select, insert, update on core.upload_batch, core.import_staging, core.column_mapping, core.validation_error to authenticated;
drop policy if exists upload_batch_admin_all on core.upload_batch;
create policy upload_batch_admin_all on core.upload_batch for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists import_staging_admin_all on core.import_staging;
create policy import_staging_admin_all on core.import_staging for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists column_mapping_admin_all on core.column_mapping;
create policy column_mapping_admin_all on core.column_mapping for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists validation_error_admin_all on core.validation_error;
create policy validation_error_admin_all on core.validation_error for all to authenticated using (core.is_admin()) with check (core.is_admin());

-- 검증 완료된 staging 행만 raw 테이블로 이동합니다. 대상 테이블/컬럼은 JSON 키로 제한됩니다.
create or replace function core.import_validated_batch(target_batch_id uuid)
returns integer language plpgsql security definer set search_path = '' as $$
declare b core.upload_batch%rowtype; row_record record; row_data jsonb; inserted_count integer := 0;
begin
  if not core.is_admin() then raise exception '관리자만 import할 수 있습니다.' using errcode = '42501'; end if;
  select * into b from core.upload_batch where batch_id = target_batch_id for update;
  if not found or b.status <> 'VALIDATED' then raise exception 'VALIDATED 상태의 batch만 import할 수 있습니다.'; end if;
  if b.import_type not in ('usage_history','inventory','item_master','supplier_master','purchase_order','goods_receipt','sales_order','business_event') then
    raise exception '지원하지 않는 import type입니다.';
  end if;
  if b.import_mode = 'replace' then
    execute format('delete from raw.%I where batch_id = $1', b.import_type) using target_batch_id::text;
  end if;
  for row_record in select row_number, mapped_data from core.import_staging where batch_id = target_batch_id and validation_status in ('SUCCESS','WARNING') order by row_number loop
    row_data := row_record.mapped_data;
    if b.import_mode = 'upsert' then
      execute format('delete from raw.%I where source_record_id = $1', b.import_type) using coalesce(row_data->>'source_record_id', row_data->>'id');
    end if;
    row_data := row_data || jsonb_build_object('batch_id', target_batch_id::text, 'source_type', 'FILE_UPLOAD', 'loaded_at', now(), 'source_record_id', target_batch_id::text || ':' || row_record.row_number::text);
    execute format('insert into raw.%I select * from jsonb_populate_record(null::raw.%I, $1)', b.import_type, b.import_type) using row_data;
    inserted_count := inserted_count + 1;
  end loop;
  update core.upload_batch set status = 'IMPORTED', imported_at = now(), success_rows = inserted_count where batch_id = target_batch_id;
  return inserted_count;
end; $$;

create or replace function core.rollback_batch(target_batch_id uuid)
returns integer language plpgsql security definer set search_path = '' as $$
declare b core.upload_batch%rowtype; deleted_count integer;
begin
  if not core.is_admin() then raise exception '관리자만 rollback할 수 있습니다.' using errcode = '42501'; end if;
  select * into b from core.upload_batch where batch_id = target_batch_id for update;
  if not found or b.status <> 'IMPORTED' or b.import_mode = 'replace' then raise exception 'rollback할 수 없는 batch입니다.'; end if;
  if b.import_type not in ('usage_history','inventory','item_master','supplier_master','purchase_order','goods_receipt','sales_order','business_event') then
    raise exception '지원하지 않는 import type입니다.';
  end if;
  execute format('delete from raw.%I where batch_id = $1', b.import_type) using target_batch_id::text;
  get diagnostics deleted_count = row_count;
  update core.upload_batch set status = 'ROLLED_BACK' where batch_id = target_batch_id;
  return deleted_count;
end; $$;

revoke all on function core.import_validated_batch(uuid), core.rollback_batch(uuid) from public, anon;
grant execute on function core.import_validated_batch(uuid), core.rollback_batch(uuid) to authenticated;
