-- STEP 2: Auth 기반 역할 권한을 데이터베이스에서 강제합니다.
-- 기존 분석·계산 뷰는 변경하지 않습니다.

create table if not exists core.app_user (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  department text,
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid not null references auth.users(id),
  action text not null,
  target_type text not null,
  target_id uuid not null,
  before jsonb,
  after jsonb,
  at timestamptz not null default now()
);

create index if not exists audit_log_target_idx
  on core.audit_log (target_type, target_id, at desc);

create or replace function core.set_app_user_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_user_set_updated_at on core.app_user;
create trigger app_user_set_updated_at
  before update on core.app_user
  for each row execute function core.set_app_user_updated_at();

-- 기존 Auth 사용자는 변경하지 않습니다. 이 트리거는 이후 신규 가입자만 등록합니다.
create or replace function core.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into core.app_user (user_id, email, name, department, role, active)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', new.raw_user_meta_data ->> 'full_name', new.email),
    new.raw_user_meta_data ->> 'department',
    'USER',
    true
  )
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function core.handle_new_auth_user();

-- security definer를 사용해 app_user RLS 순환 참조 없이 현재 사용자의 활성 ADMIN 여부를 판별합니다.
create or replace function core.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
      from core.app_user
     where user_id = auth.uid()
       and role = 'ADMIN'
       and active = true
  );
$$;

-- 공개 함수 실행 권한을 제거하고 필요한 로그인 역할에만 RPC 실행을 허용합니다.
revoke all on function core.set_app_user_updated_at() from public, anon, authenticated;
revoke all on function core.handle_new_auth_user() from public, anon, authenticated;
revoke all on function core.is_admin() from public, anon;
grant execute on function core.is_admin() to authenticated;

-- 익명 사용자는 업무 스키마·뷰·테이블·함수를 사용할 수 없습니다.
revoke all on schema core, analytics from public, anon;
revoke all privileges on all tables in schema core from public, anon;
revoke all privileges on all tables in schema analytics from public, anon;
revoke all privileges on all sequences in schema core from public, anon;
revoke all privileges on all functions in schema core from public, anon;
alter default privileges in schema core revoke all on tables from public, anon;
alter default privileges in schema analytics revoke all on tables from public, anon;
alter default privileges in schema core revoke execute on functions from public, anon;

-- 로그인 사용자는 analytics 뷰만 기본 조회할 수 있습니다.
grant usage on schema core, analytics to authenticated;
revoke all privileges on all tables in schema core from authenticated;
grant select on all tables in schema analytics to authenticated;
alter default privileges in schema analytics grant select on tables to authenticated;

-- core 조회·수정 권한은 필요한 테이블로 최소화하고, 실제 허용 여부는 RLS가 판정합니다.
grant select on core.app_user, core.audit_log to authenticated;
grant select, insert, update, delete on core.leadtime_plan, core.usage_profile to authenticated;

alter table core.app_user enable row level security;
alter table core.audit_log enable row level security;
alter table core.leadtime_plan enable row level security;
alter table core.usage_profile enable row level security;

-- 과거 수업용 전체 허용 정책을 제거합니다.
drop policy if exists "수업용 전체 허용" on core.leadtime_plan;
drop policy if exists "수업용 전체 허용" on core.usage_profile;

drop policy if exists app_user_self_or_admin_select on core.app_user;
create policy app_user_self_or_admin_select
  on core.app_user
  for select
  to authenticated
  using ((auth.uid() = user_id and active = true) or core.is_admin());

drop policy if exists app_user_admin_update on core.app_user;
create policy app_user_admin_update
  on core.app_user
  for update
  to authenticated
  using (core.is_admin())
  with check (core.is_admin());

drop policy if exists audit_log_admin_select on core.audit_log;
create policy audit_log_admin_select
  on core.audit_log
  for select
  to authenticated
  using (core.is_admin());

drop policy if exists leadtime_plan_admin_all on core.leadtime_plan;
create policy leadtime_plan_admin_all
  on core.leadtime_plan
  for all
  to authenticated
  using (core.is_admin())
  with check (core.is_admin());

drop policy if exists usage_profile_admin_all on core.usage_profile;
create policy usage_profile_admin_all
  on core.usage_profile
  for all
  to authenticated
  using (core.is_admin())
  with check (core.is_admin());

create or replace function core.admin_update_user(
  target_user_id uuid,
  next_role text,
  next_active boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id uuid := auth.uid();
  normalized_role text := upper(trim(next_role));
  previous_user core.app_user%rowtype;
  updated_user core.app_user%rowtype;
begin
  if not core.is_admin() then
    raise exception '관리자만 사용자 권한을 변경할 수 있습니다.' using errcode = '42501';
  end if;

  if normalized_role is null or normalized_role not in ('ADMIN', 'USER') then
    raise exception '허용되지 않은 역할입니다.' using errcode = '22023';
  end if;

  if next_active is null then
    raise exception '활성 상태를 지정해야 합니다.' using errcode = '22023';
  end if;

  select * into previous_user
    from core.app_user
   where user_id = target_user_id;

  if not found then
    raise exception '대상 사용자를 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  if target_user_id = actor_id and normalized_role <> 'ADMIN' then
    raise exception '자신의 관리자 역할은 낮출 수 없습니다.' using errcode = '42501';
  end if;

  if target_user_id = actor_id and next_active = false then
    raise exception '자신을 비활성화할 수 없습니다.' using errcode = '42501';
  end if;

  update core.app_user
     set role = normalized_role,
         active = next_active
   where user_id = target_user_id
   returning * into updated_user;

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (
    actor_id,
    'ADMIN_UPDATE_USER',
    'app_user',
    target_user_id,
    to_jsonb(previous_user),
    to_jsonb(updated_user)
  );
end;
$$;

revoke all on function core.admin_update_user(uuid, text, boolean) from public, anon;
grant execute on function core.admin_update_user(uuid, text, boolean) to authenticated;
